import type { MarkdownIt } from 'markdown-it';

export interface TaskPreviewOptions {
  interactiveTasks?: boolean;
  taskRevision?: number;
}

/** Attach source positions only to checkboxes generated by the Markdown task-list parser. */
export function interactiveTasks(md: MarkdownIt) {
  md.core.ruler.after('github-task-lists', 'lownotes-task-positions', (state) => {
    if (!state.env?.interactiveTasks || typeof state.env.taskSource !== 'string') return;
    const source: string = state.env.taskSource;
    const lines = source.split(/\r\n|\n|\r/);
    const starts = [0];
    for (const match of source.matchAll(/\r\n|\n|\r/g)) starts.push(match.index! + match[0].length);
    for (const token of state.tokens) {
      if (token.type !== 'inline' || !token.map) continue;
      const checkbox = token.children?.find((child) => child.type === 'html_inline'
        && child.content.startsWith('<input class="task-list-item-checkbox"'));
      if (!checkbox) continue;
      const line = token.map[0];
      const marker = /\[([ xX])\](?=[ \t])/.exec(lines[line] ?? '');
      if (!marker) continue;
      const offset = starts[line] + marker.index + 1;
      checkbox.content = checkbox.content.replace(' disabled="" ', ' ')
        .replace('type="checkbox"', `type="checkbox" data-task-offset="${offset}" data-task-checked="${marker[1] !== ' '}" data-task-revision="${state.env.taskRevision ?? 0}"`);
    }
  });
}

/** A one-character edit preserves all formatting, selection mapping and collaborative history. */
export function taskCheckboxChange(source: string, offset: number, wasChecked: boolean, checked: boolean) {
  if (!Number.isSafeInteger(offset) || offset < 1 || offset >= source.length - 2
    || source[offset - 1] !== '[' || source[offset + 1] !== ']'
    || !/[ \t]/.test(source[offset + 2]) || !/[ xX]/.test(source[offset])
    || (source[offset] !== ' ') !== wasChecked || checked === wasChecked) return null;
  return { from: offset, to: offset + 1, insert: checked ? 'x' : ' ' };
}
